### ISSUE TITLE
Masters

### ISSUE THREAD

**Issue by oskarrough** [internet4000/explorer-discogs#12]
How does a master relate to a release?

At the moment it's blank https://explorer-discogs.netlify.com/masters/74177

**Comment by hugurp** [comment]
> The Master resource represents a set of similar Releases. Masters (also known as “master releases”) have a “main release” which is often the chronologically earliest.
https://www.discogs.com/developers/#page:database,header:database-master-release

We also have to investigate if the videos are the same betwwen releases and master.

What interests us here is the release infos, its track names and infos, and the associated videos.

In the end, which one is the earlieast or whatnot is not so important. Maybe we can show the master info if available. Not sure, let's go to the simplest.

**Comment by oskarrough** [comment]
In order to answer this question maybe we should implement the master template? So we can see it compares.
