### ISSUE TITLE
Provide a User-Agent string

### ISSUE THREAD

**Issue by oskarrough** [internet4000/explorer-discogs#8]
Your application must provide a User-Agent string that identifies itself 

https://www.discogs.com/developers/#page:home,header:home-general-information

**Comment by hugurp** [comment]
Trying this but getting `Refused to set unsafe header "user-agent"`.

Seems to be the issue: https://stackoverflow.com/questions/7210507/ajax-post-error-refused-to-set-unsafe-header-connection

Therefore seems that we need to build, and *host* a proxy to make the requests.

That was also required to hide the application key and scret that we have rn in clear in the repo.

**Comment by oskarrough** [comment]
Ah, did not know about that. So you can only set `User-Agent` when the request is made on a server (proxy)? If so, let's make a new issue to create a proxy.

**Comment by oskarrough** [comment]
Here they also say it's impossible client-side. We need node.js (or whatever server-side).

https://www.discogs.com/forum/thread/737881#7320150
https://github.com/bartve/disconnect

**Comment by oskarrough** [comment]
Fixed by adding the proxy #21
